//
//  LoginViewController.swift
//  DemoVIPER
//
//  Created Thi Vo on 2018/9/19.
//  Copyright © 2018 UIT. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: UIViewController, LoginViewProtocol {
	var presenter: LoginPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func login(_ sender: Any) {
        self.presenter?.btnLoginClick()
    }
    
    func loginSuccess() {
        // Move screen
        self.showAlert()
    }
    
    func showAlert() {
        // create the alert
        let alert = UIAlertController(title: "", message: "The App will move screen...", preferredStyle: UIAlertControllerStyle.alert)
        // add an action (button)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { _ in
            // Move screen
            
        }))
        // show the alert
        self.present(alert, animated: true, completion: nil)
    }
}
