//
//  LoginViewController.swift
//  DemoVIPER
//
//  Created Thi Vo on 2018/9/19.
//  Copyright © 2018 UIT. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: UIViewController, LoginViewProtocol {
	var presenter: LoginPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBOutlet weak var txtPassword: UITextField!
    @IBOutlet weak var txtEmail: UITextField!
    @IBAction func login(_ sender: Any) {
        self.presenter?.btnLoginClick()
    }
    
    func loginSuccess() {
        // Move screen
        showAlert()
    }
    
    func showAlert() {
        // create the alert
        let alert = UIAlertController(title: Constants.titleShowAlertMessage, message: Constants.showAlertSucessFull, preferredStyle: UIAlertControllerStyle.alert)
        // add an action (button)
        alert.addAction(UIAlertAction(title: Constants.buttonShowAlertOK, style: .default, handler: { _ in
            // Move screen
            self.presenter?.okButtonAlertClick()
        }))
        // show the alert
        self.present(alert, animated: true, completion: nil)
    }
}
