//
//  HomeInteractor.swift
//  DemoVIPER
//
//  Created Anh Tran on 9/19/18.
//  Copyright © 2018 UIT. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Alamofire
import ObjectMapper
import AlamofireObjectMapper

class HomeInteractor: HomeInteractorInputProtocol {
    
    weak var presenter: HomeInteractorOutputProtocol?
    
    func callAPIGetImages(){
        self.getImageFromAPI { (success, list) in
            if success {
                // show list in View
                self.presenter?.callAPISuccess(list: list)
            } else {
                // call show alert
                self.presenter?.callAPIFail()
            }
        }
    }

    func getImageFromAPI(completion: @escaping (_ result: Bool, _ images: [SplashbaseImage]) -> Void) {
        let URL = Constants.linkImage
        Alamofire.request(URL).responseArray(keyPath: Constants.keyPathAlamofire) { (response: DataResponse<[SplashbaseImage]>) in
            let forecastArray = response.result.value
            if let forecastArray = forecastArray{
                CoreDataImage.shared.saveData(list: forecastArray)
                completion(true, forecastArray)
            } else {
                completion(false, [])
            }
        }
    }
    
    func deleteLocalDataImages() {
        CoreDataImage.shared.deleteData()
    }
    func fecthLocalImages() {
        let images = CoreDataImage.shared.fetchData()
        self.presenter?.getImageLocalSuccess(list: images ?? [])
    }
   
}
