//
//  HomeProtocols.swift
//  DemoVIPER
//
//  Created Anh Tran on 9/19/18.
//  Copyright © 2018 UIT. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: class {
}
//MARK: Presenter -
protocol HomePresenterProtocol: class {
    /* ViewController ->  Presenter*/
    var interactor: HomeInteractorInputProtocol? { get set }
    func getImages()
    func deleteLocal()
    func fecthLocalImage()
}

//MARK: Interactor -
protocol HomeInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func callAPISuccess(list: [SplashbaseImage])
    func callAPIFail()
    func getImageLocalSuccess(list: [SplashbaseImage])
}

protocol HomeInteractorInputProtocol: class {

    var presenter: HomeInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func callAPIGetImages()
    func deleteLocalDataImages()
    func fecthLocalImages()
}

//MARK: View -
protocol HomeViewProtocol: class {

    var presenter: HomePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func getImageFail()
    func getImageSuccess(list: [SplashbaseImage])
    func getLocalSuccess(list: [SplashbaseImage])
}
