//
//  HomePresenter.swift
//  DemoVIPER
//
//  Created Anh Tran on 9/19/18.
//  Copyright © 2018 UIT. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter: HomePresenterProtocol, HomeInteractorOutputProtocol {
    
    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorInputProtocol?
    private let router: HomeWireframeProtocol
    
    init(interface: HomeViewProtocol, interactor: HomeInteractorInputProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getImages() {
        self.interactor?.callAPIGetImages()
    }
    
    func callAPISuccess(list: [SplashbaseImage]) {
        self.view?.getImageSuccess(list: list)
    }
    
    func callAPIFail() {
        print(Constants.showAlertAPIFail)
    }
    
    func deleteLocal() {
        self.interactor?.deleteLocalDataImages()
    }
    
    func fecthLocalImage() {
        self.interactor?.fecthLocalImages()
    }
    
    func getImageLocalSuccess(list: [SplashbaseImage]) {
        self.view?.getLocalSuccess(list: list)
    }
    
    func logOut() {
        self.router.logout()
    }
    
    func ImageLoad() {
        self.router.moveImageView()
    }
    
}
